### ISSUE TITLE
Pet inventory and pet modularity

### ISSUE THREAD

**Issue by benquach16** [benquach16/CS180#10]
Set up pets so that we can support changing their parts easily and quickly. Mostly database stuff but we also want art and a way to easily display our finished customized pet.

**Comment by benquach16** [comment]
@cdeng001

**Comment by cdeng001** [comment]
Tmr i can work on getting one example going, im going to make the parts (head, arms body.. etc) as just circles and rectangles

**Comment by benquach16** [comment]
Sounds good.
