### ISSUE TITLE
Login System - Frontend

### ISSUE THREAD

**Issue by benquach16** [benquach16/CS180#2]
Setup a page for logins using javascript and html

**Comment by cdeng001** [comment]
im going to set one up, im going to use bootstrap to just make it look somewhat decent. We can change the css style attributes later after we get a project but for now im going to use a bootstrap css template

**Comment by benquach16** [comment]
that's fine. we just need an html page for now

**Comment by benquach16** [comment]
@dylanjay @ThatZaZaBean @mderu assigned to you

**Comment by benquach16** [comment]
Resolved
