### ISSUE TITLE
Create API for selected pet

### ISSUE THREAD

**Issue by benquach16** [benquach16/CS180#34]

**Comment by cdeng001** [comment]
sry, can you explain a bit more?

**Comment by benquach16** [comment]
this is just a way to quickly display the currently selected pet wherever in the site. this is good since it would let users have an avatar of their pet wherever and let the game know what pet is selected

**Comment by cdeng001** [comment]
has this been resolved?

**Comment by benquach16** [comment]
mostly. it just stores it in a db
